### ISSUE TITLE
mingw64 build error

### ISSUE THREAD

**Issue by phpstatic** [sftcd/openssl#12]
build from master branch with x86_64-w64-mingw32-gcc, get this error:

```sh
../ssl/statem/extensions_srvr.c:18:10: fatal error: netinet/in.h: No such file or directory
 #include <netinet/in.h>
          ^~~~~~~~~~~~~~
```

**Comment by sftcd** [comment]
github CI now has some windows builds (though not mingw64) which pass so this should be ok now
