### ISSUE TITLE
How can I generate ECH keys for testing with nginx?

### ISSUE THREAD

**Issue by ckcr4lyf** [sftcd/openssl#26]
I am following the March 2023 steps here: https://github.com/sftcd/openssl/blob/9e66beb759d274f3069e19cc96c793712e83122c/esnistuff/nginx.md?plain=1#L172

I've generated some fake CA / website certs via `make-example-ca.sh` , which seems to be fine. However if I try `testnginx-draft-13.sh` , I get the following:

```
Executing:  /home/ubuntu/code/nginx/objs/nginx -c /home/ubuntu/code/openssl-for-nginx/esnistuff/nginxmin-draft-13.conf
nginx: [emerg] load_echkeys, error opening /home/ubuntu/code/openssl-for-nginx/esnistuff/echkeydir at 1463
nginx: [emerg] Hey some bad ech stuff happened at 1544
```

I tried to search around a bit, but not too sure how to populate this directory with the ECH keys. Any advice would be great.

**Comment by ckcr4lyf** [comment]
Nice, it seems to have worked!

```
./echcli.sh Summary:
Looks like ECH worked ok
ECH: success: outer SNI: 'example.com', inner SNI: 'foo.example.com'
```

Thanks for the help. I'll play around with it more and ask questions if  need be!

**Comment by sftcd** [comment]
On 16/11/2023 09:33, Raghu Saxena wrote:
> Nice, it seems to have worked!

Excellent! Any feedback on the HOWTO text welcome too.

S.
