### ISSUE TITLE
mk_esnikeys.c has compile-time errors on FreeBSD

### ISSUE THREAD

**Issue by niallor** [sftcd/openssl#5]
When following HOWTO for building ESNI-aware OpenSSL and curl, `make` fails
in *esnistuff* directory, with following compiler messages.

```
mk_esnikeys.c:417:54: error: incomplete definition of type 'struct sockaddr_in'
                          &((struct sockaddr_in *)sa)->sin_addr,
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
mk_esnikeys.c:417:37: note: forward declaration of 'struct sockaddr_in'
                          &((struct sockaddr_in *)sa)->sin_addr,
                                    ^
mk_esnikeys.c:421:55: error: incomplete definition of type 'struct sockaddr_in6'
                          &((struct sockaddr_in6 *)sa)->sin6_addr,
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
mk_esnikeys.c:421:37: note: forward declaration of 'struct sockaddr_in6'
                          &((struct sockaddr_in6 *)sa)->sin6_addr,
                                    ^
2 errors generated.
*** Error code 1

Stop.
make: stopped in /tmp/tmp.nB2w3U9p/openssl/esnistuff
$ 

```

**Comment by niallor** [comment]
Specific version of HOWTO that I was following: https://github.com/niallor/curl/blob/master/ESNI-README.md

I suspect that this problem is caused by some difference in header files between Linux (Ubuntu) and FreeBSD.

**Comment by sftcd** [comment]
Just to note that with a bit of luck this may disappear as an issue - if HTTPSSVC is adopted then that code will no longer be needed in OpenSSL as the IP address stuff  will no longer be needed inside the ESNI public key structutre.

**Comment by sftcd** [comment]
Closing this as mk_esnikeys.c has been dropped as part of the ESNI->ECH changes.
