### ISSUE TITLE
make test failed at Ubuntu 18.04.1

### ISSUE THREAD

**Issue by pol4bear** [sftcd/openssl#6]
Hi, I tried to build openssl but make test failed at Ubuntu 18.04.1. How can I fix it?
`$ uname -a   
Linux pol4bear 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`   

../test/recipes/95-test_external_pyca.t ............ skipped: No external tests in this configuration   
../test/recipes/99-test_ecstress.t ................. ok      
../test/recipes/99-test_fuzz.t ..................... ok        
   
Test Summary Report   
-------------------   
../test/recipes/01-test_symbol_presence.t        (Wstat: 256 Tests: 4 Failed: 1)   
  Failed test:  4   
  Non-zero exit status: 1   
Files=176, Tests=1662, 118 wallclock secs ( 1.64 usr  0.14 sys + 91.41 cusr  5.62 csys = 98.81 CPU)
Result: FAIL   
Makefile:198: recipe for target '_tests' failed   
make[1]: *** [_tests] Error 1   
make[1]: Leaving directory '/home/pol4bear/ESNI/openssl'   
Makefile:196: recipe for target 'tests' failed   
make: *** [tests] Error 2

**Comment by sftcd** [comment]
Hiya,

Checking. I did a bit of function renaming yesterday. That
might have caused an issue. ``make test`` works locally for
me though, so maybe if you try: ``./config; make update;
make clean; make; make test`` it'll work.

Cheers,
S.

**Comment by sftcd** [comment]
Hiya,

Yeah, I had omitted committing a change to libssl.num which
is part of the build. Seems to work now from a clean clone.

Cheers,
S.

**Comment by pol4bear** [comment]
Thanks for fast feedback! Have a nice day I appreciate for your help.

**Comment by sftcd** [comment]
No probs. I'll close this now .
